### ISSUE TITLE
Support higher number of options

### ISSUE THREAD

**Issue by TwiN** [TwiN/go-choice#4]
When there's more options than what can fit on the terminal, `...` should be added as the first and last option and should allow users to change the page.

**Comment by BATUELMEJOR2010** [comment]
HELLO FRIEND TWINPRODUCTION, I WOULD LIKE TO INFORM YOU THAT THE XAT RAID DOESN'T WORK, IF YOU COULD DESIGN ME A NEW PROGRAM
